feat(rust): migrate platform_helpers into Rust
This is a verbatim move; no code is minimized or removed in this change.
Exception: `#include`s which were not necessary before and which cannot
now work in platform_helpers.S are removed.

Change-Id: Id41da4a98b569ec6d3560e9c828c1498329558dc
Signed-off-by: Chris Palmer <palmer@google.com>