fix(ffa): fix retval for FFA_VERSION when bit 31 of version is set
Since FF-A specification v1.3 ALP5 [0], FFA_VERSION is required to return
INVALID_PARAMETER when bit 31 of the input version parameter is set.
The TFTF test has been updated accordingly [1].

As a result, test_ffa_version_bit31() now fails with RF-A because
it still returns NOT_SUPPORTED in this case, causing a CI failure:

  Running test suite 'FF-A Setup and Discovery'
  Description: Test FF-A Setup and Discovery interfaces
  ...
  > Executing 'Setting bit 31 in input version'
  ERROR: Invalid FF-A call from Normal World Invalid version 2147549187
  TEST COMPLETE  Failed

  Input Version: 0x80010003
  Return: 0xffffffff
  Expected: 0xfffffffd

To fix this, return INVALID_PARAMETER in this case to align with the
specification.

Link: [0] https://support.arm.com/documentation/den0077/latest
Link: [1] https://github.com/TrustedFirmware-A/tf-a-tests/commit/b4b63cfd50f8c4c3541f3d9cff93784c0b7a59ca
Signed-off-by: Yeoreum Yun <yeoreum.yun@arm.com>
Change-Id: I2c508c85ce51f39065bb6e553aa9a67aebf28435